services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/backend
    command: >
      bash -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/.venv
      - ./frontend/templates:/app/frontend/templates
    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    environment:
      - DEBUG=True
      - USE_POSTGRES=True

    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure

volumes:
  pgdata: