services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
   
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/backend/staticfiles
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=False
      - USE_POSTGRES=True
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/staticfiles
    depends_on:
      - backend
    restart: on-failure

volumes:
  pgdata:
  static_volume: