SLUG_MAX_LENGTH_ERROR = 'Slug exceeds maximum length of 50 characters.'
SLUG_DUPLICATE_ERROR = 'The slug is already in use. Please choose a different one.'
URL_INVALID_ERROR = 'Please enter a valid URL.'
PASSWORD_MAX_LENGTH_ERROR = 'Password exceeds maximum length of 64 characters.'
CREATED_LINK_SUCCESS = 'Link created successfully.'
ORIGINAL_URL_REQUIRED_ERROR = 'original_url is required.'
JSON_PARSE_ERROR = 'Invalid JSON format.'
