# Generated by Django 5.2.3 on 2025-06-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='original_url',
            field=models.URLField(error_messages={'invalid': 'Please enter a valid URL.'}, max_length=2048),
        ),
        migrations.AlterField(
            model_name='link',
            name='password',
            field=models.CharField(blank=True, error_messages={'max_length': 'Password exceeds maximum length of 64 characters.'}, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.SlugField(blank=True, error_messages={'max_length': 'Slug exceeds maximum length of 50 characters.', 'unique': 'The slug is already in use. Please choose a different one.'}, unique=True),
        ),
    ]
