# Generated by Django 5.2.3 on 2025-06-29 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_original_url_alter_link_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='password',
            field=models.CharField(blank=True, error_messages={'max_length': 'Password exceeds maximum length of 64 characters.'}, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='UTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100)),
                ('medium', models.CharField(blank=True, max_length=100)),
                ('campaign', models.CharField(blank=True, max_length=100)),
                ('term', models.CharField(blank=True, max_length=100)),
                ('content', models.CharField(blank=True, max_length=100)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utms', to='links.link')),
            ],
        ),
    ]
