# Generated by Django 5.2.3 on 2025-06-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_link_click_count_alter_link_password_utm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UTM',
        ),
    ]
