# Generated by Django 5.2.3 on 2025-06-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_link_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
