# Generated by Django 5.2.3 on 2025-07-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_link_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='original_url_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
