name: Django CI Tests

on: [push, pull_request]

jobs:
  native-pytest:
    name: Native Python Pytest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: "True"
      USE_POSTGRES: "False"
      ALLOWED_HOSTS: localhost,127.0.0.1

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: pip install uv

      - name: Install backend dependencies
        run: uv sync

      - name: Run migrations
        run: uv run python manage.py migrate

      - name: Run pytest
        run: uv run pytest -v --tb=short --maxfail=5 --disable-warnings
